baseurl = "https://mummanajagadeesh.github.io/ORIGO2K25/"
defaultContentLanguage = "en"
languageCode = "en"
title = "ORIGO RESOURCES"
theme = "dream"

[services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = "G-CPENBPWFNZ"

[params]
zenMode = false

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "RIG-NITC"
# description = ""
avatar = "img/avatar.png"
headerTitle = "ORIGO24"
motto = "Because all we do is robotics"

footerBottomText = "ðŸ¤– Powered by pure love for robotics"

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2025

favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
noDefaultSummaryCover = true
showTableOfContents = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
# showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

[params.navItems]
series = { href = "https://rignitc.github.io/blogs/", target = "_blank", icon = "planet", title = "Blog" }
github = { href = "https://github.com/rignitc", target = "_blank", icon = "logo-github", title = "GitHub" }

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyyå¹´MMæœˆddæ—¥"

# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#         unsafe = true